In [3]:
#1

symbols = "$*&!@"
codes = []

for symbol in symbols:
  codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [5]:
#2

symbols = "$*&!@"

codes = [ord(symbol) for symbol in symbols]

print(codes)

[36, 42, 38, 33, 64]


In [7]:
#3

x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [8]:
#4

symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [9]:
#5

symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c>64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>> <map object at 0x7c7505c76830>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [10]:
#6

colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
  for size in sizes:
    print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [11]:
#7

symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [13]:
#8

colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirts in ('{} {}'. format(c, s) for s in sizes for c in colors):
  print(tshirts)

black S
white S
black M
white M
black L
white L


In [14]:
#9

lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
                ('BRA', 'CE342567'),
                ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
  print('%s/%s' % passport)
  print('{}/{}'.format(passport[0], passport[1]))
  print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [15]:
#10

for country, _ in traveler_ids:
  print(country)

USA
BRA
ESP


In [16]:
#11

lax_coordinates = (33.9425, -118.408056)
latitude, longtitude = lax_coordinates
print(latitude)
print(longtitude)

33.9425
-118.408056


In [17]:
#12

a = 10; b = 20
b, a = a, b
print(a, b)

20 10


In [21]:
#13-1

divmod(20, 8)

(2, 4)

In [22]:
#13-2

t = (20, 8)
divmod(*t)

(2, 4)

In [23]:
#13-3

quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [26]:
#14

import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [28]:
#15-1

a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [29]:
#15-2

a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [30]:
#15-3

a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [31]:
#16-1
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [33]:
#16-2
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [34]:
#17
metro_areas = [
    ("Tokyo", "JP", 36.933, (35, 139)),
    ("Delhi NCR", "IN", 21, (28, 77)),
    ("Mexico City", "Mx", 20, (19, -99)),
    ("New York_Newark", "US", 20, (40, -74)),
    ("Sao Paulo", "BR", 19, (-23, -46))
]

print("{:15}  | {:^9} | {:^9}".format('', 'lat.', 'long.'))
fmt = '{:15}  | {:9.4f} |{:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
  if longi <= 0:
    print(fmt.format(name, lat, longi))

                 |   lat.    |   long.  
Mexico City      |   19.0000 | -99.0000
New York_Newark  |   40.0000 | -74.0000
Sao Paulo        |  -23.0000 | -46.0000


In [42]:
#18-1
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))

tokyo


City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))

In [44]:
#18-2
tokyo.population

36.933

In [45]:
#18-3
tokyo.coordinates

(35.689, 139.691)

In [46]:
#18-4
tokyo[1]

'JP'

In [49]:
#19-1
City._fields

('name', 'country', 'population', 'coordinates')

In [50]:
#19-2
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('delhi NCR', 'IN', 29.935, LatLong(28.613, 77.208))

In [51]:
#19-3
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'delhi NCR',
 'country': 'IN',
 'population': 29.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [53]:
#19-4
for key, value in delhi._asdict().items():
  print(key + ':', value)

name: delhi NCR
country: IN
population: 29.935
coordinates: LatLong(lat=28.613, long=77.208)


In [56]:
#20-1
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [57]:
#20-2
l[2:]

[30, 40, 50, 60]

In [58]:
#20-3
l[:3]

[10, 20, 30]

In [59]:
#20-4
l[3:]

[40, 50, 60]

In [60]:
#21
invoice = """
0.....6..................25........33......40.......
1909  Pimorni               $17.50    3      $52.50
1489  6mm Tactile           $4.95     2      $9.90
"""

SKU  = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
  print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5 Pimorni            
   $4.95 6mm Tactile        
 


In [61]:
#22-1
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
#22-2
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [63]:
#22-3
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [64]:
#22-4
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [65]:
#23
l[2:5] = 100

TypeError: must assign iterable to extended slice

In [66]:
#24
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [67]:
#25-1
l = [1, 2, 3]
l*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [68]:
#25-2
5*'abcd'

'abcdabcdabcdabcdabcd'

In [69]:
#26-1
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [70]:
#26-2
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [71]:
#27-1
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [72]:
#27-2
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [73]:
#28
row = ['_'] * 3
board = []
for i in range(3):
  board.append(row)

board[1][2] = 'X'

board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [74]:
#29
board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)

print(board)

board[2][0] = 'X'

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [76]:
#30-1
l = [1, 2, 3]
id(l)

136842036898816

In [77]:
#30-2
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [78]:
30-3
id(l)

136842036898816

In [79]:
#31-1
t = (1, 2, 3)
id(t)

136842037996736

In [81]:
#30-2
t *= 2
id(t)

136842039964816

In [82]:
#32
t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60]

"""
a. t는 (1, 2, [30, 40, 50, 60])이 된다.
b. '튜플 객체는 항목 할당을 지원하지 않는다'는 메세지와 함께 TypeError가 발생한다.
c. a와 b둘 다 틀리다.
d. a와 b둘 다 맞다.
"""

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [83]:
#33
print(t)

(1, 2, [30, 40, 50, 60])


In [84]:
#34-1
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [85]:
#34-2
fruits

['grape', 'raspberry', 'apple', 'banana']

In [86]:
#34-3
sorted(fruits, reverse = True)

['raspberry', 'grape', 'banana', 'apple']

In [87]:
#34-4
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [88]:
#35-1
sorted(fruits, key = len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [89]:
#35-2
fruits

['grape', 'raspberry', 'apple', 'banana']

In [90]:
#35-3
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [91]:
#36
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]

0.49540635344507633

In [92]:
#37-1
with open('floats.bin', 'wb') as f:
  floats.tofile(f)

In [93]:
#37-2
floats2 = array('d')
with open('floats.bin', 'rb') as f:
  floats2.fromfile(f, 10**7)

floats2[-1]

0.49540635344507633

In [94]:
#37-3
floats == floats2

True

In [96]:
#38-1
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [98]:
#38-2
memv[0]

-2

In [101]:
#38-3
memv_oct = memv.cast('B')
memv_oct.tolist()


[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [102]:
#38-4
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [104]:
#39-1
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [105]:
#39-2
type(a)

numpy.ndarray

In [106]:
#40-1
a.shape

(12,)

In [107]:
#40-2
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
#41-1
a[2]

array([ 8,  9, 10, 11])

In [110]:
#41-2
a[2, 1]

np.int64(9)

In [111]:
#41-3
a[:, 1]

array([1, 5, 9])

In [112]:
#42
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])